### ISSUE TITLE
Installation Error, possible issue with setuptools version

### ISSUE THREAD

**Issue by callaband** [biocore/q2-katharoseq#10]
I am using qiime2-2023.2 and trying to install katharoseq to use with some 16S V4 urine samples. 

Typical installation: 
`git clone https://github.com/biocore/q2-katharoseq.git`

`cd q2-katharoseq`

`pip install -e .`

Here is the error I get, sounds like an issue with the version of setuptools:

Obtaining file:///Users/callaband/Desktop/UCSD/KnightLab/q2-katharoseq
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running egg_info
      /opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('initial+1.g4897535') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      /opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: 'initial+1.g4897535'.
              !!
      
      
              ###################
              # Invalid version #
              ###################
              'initial+1.g4897535' is not valid according to PEP 440.
      
              Please make sure specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
      
      !!
      
        warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/callaband/Desktop/UCSD/KnightLab/q2-katharoseq/setup.py", line 15, in <module>
          setup(
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 220, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/opt/anaconda3/envs/qiime2-2023.2/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'initial-1.g4897535'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by antgonza** [comment]
Not sure why this is happening but I was able to reproduce it my local installation using: qiime2-2023.5. 

Anyway, this worked:
`pip install https://github.com/biocore/q2-katharoseq/archive/refs/heads/master.zip`; could you give it a try?

**Comment by callaband** [comment]
Works - thank you!
